[book]
authors = ["Chiro Hiro"]
language = "en"
multilingual = false
src = "src"
title = "Orochi Network's Cookbook"
[output.html]
mathjax-support = true
[output.html.fold]
enable = false
[preprocessor.bib]
bibliography = "refs.bib"